Roadmap features: Mqtt broker/subscriber support
OS2iot/OS2IoT-frontend pull request #137
Opened 2023-05-11 08:28 UTC by fcv-iteratorIt

Also includes a csv export of all devices in an application

2023-05-11 10:02 UTC, augusthjerrild commented on src/app/applications/bulk-import/bulkMapping.ts
For at følge den samme syntax burde navnet nok være bulk-mapping.ts

2023-05-16 12:01 UTC, augusthjerrild requested changes

2023-05-17 06:09 UTC, fcv-iteratorIt commented on src/app/applications/bulk-import/bulkMapping.ts
renamed

2023-05-17 06:10 UTC, fcv-iteratorIt commented on src/app/applications/bulk-import/bulkMapping.ts
> +    //return new IotDevice();
Deleted

2023-05-17 06:13 UTC, fcv-iteratorIt commented on src/app/applications/iot-devices/iot-device-detail/iot-device-detail-generic/iot-device-detail-generic.component.html
> +                <app-batteri-status *ngIf="device.type === DeviceType.LORAWAN; else noBatteryStatus" [color]="batteryStatusColor"
Removed the elements never shown

2023-05-17 06:14 UTC, fcv-iteratorIt commented on src/app/applications/iot-devices/iot-device-detail/iot-device-detail-generic/iot-device-detail-generic.component.html
> +            <ng-container  *ngIf="device.type === DeviceType.GENERIC_HTTP">
Removed

2023-05-17 06:15 UTC, fcv-iteratorIt commented on src/app/applications/iot-devices/iot-device-detail/iot-device-details-mqtt-broker/iot-device-details-mqtt-broker.component.html
> +  <!--  <p><strong>{{ 'QUESTION.MQTT.PASSWORD-LABEL' | translate }}</strong>{{ device.mqttBrokerSettings.mqttPassword }}</p>-->
Removed

2023-05-17 06:20 UTC, fcv-iteratorIt commented on src/app/applications/iot-devices/iot-device-detail/iot-device-details-mqtt-broker/iot-device-details-mqtt-broker.component.html
> +    <button [cdkCopyToClipboard]="device.mqttBrokerSettings.caCertificate" class="btn">{{ 'IOTDEVICE.MQTT.COPY-TO-CLIPBOARD' | translate }}</button>
Added some spacing below the button, there is a feature request on a download button, will be added

2023-05-17 06:21 UTC, fcv-iteratorIt commented on src/app/applications/iot-devices/iot-device-edit/iot-device-edit.component.html
> +        <mat-checkbox [(ngModel)]="iotDevice.lorawanSettings.skipFCntCheck" name="skipFCntCheck" id="skipFCntCheck">
Yes

2023-05-17 06:22 UTC, fcv-iteratorIt commented on src/app/applications/iot-devices/iot-device-edit/iot-device-edit.component.ts
> +  public console = console;
Nothing anymore, removed

2023-05-17 06:23 UTC, fcv-iteratorIt commented on src/app/applications/iot-devices/iot-device-edit/mqtt-device-edit/mqtt-authentication-select/mqtt-authentication-select.component.html
> +      [icon]="faQuestionCircle"
It will be changed to be possible to find it again (it is requested in the csv export)

2023-05-17 06:24 UTC, fcv-iteratorIt commented on src/app/applications/iot-devices/iot-device-edit/mqtt-device-edit/mqtt-authentication-select/mqtt-authentication-select.component.ts
> +import { IotDevice } from '@applications/iot-devices/iot-device.model';
Removed

2023-05-17 06:24 UTC, fcv-iteratorIt commented on src/app/applications/iot-devices/iot-device-edit/mqtt-device-edit/mqtt-device-edit.component.ts
> +  AfterContentInit,
Removed the unused ones

2023-05-17 06:26 UTC, fcv-iteratorIt commented on src/app/applications/iot-devices/iot-devices-tab/iot-devices-tab.component.ts
> +import { Download, download } from '@shared/helpers/download.helper';
Removed

2023-05-17 06:27 UTC, fcv-iteratorIt commented on src/app/applications/iot-devices/iot-devices-tab/iot-devices-tab.component.ts
> +    private restService: RestService,
Removed

2023-05-17 06:29 UTC, fcv-iteratorIt commented on src/app/shared/enums/qos.enum.ts
Not for now, if datatarget is updated to use an enum it can be added back. Deleted for now

2023-05-17 06:29 UTC, fcv-iteratorIt commented on src/assets/i18n/da.json
> +    "CREATE": "Opret LoRaWAfN gateway"
You tell no one

2023-05-17 06:30 UTC, fcv-iteratorIt commented on src/assets/i18n/da.json
> +    "MQTT_SUBSCRIBER": "MQTT Client",
Broker it is

2023-05-17 06:31 UTC, fcv-iteratorIt commented on src/assets/i18n/da.json
> +      "SUBTYPE": "Enheds type",
Fixed

2023-05-17 06:32 UTC, fcv-iteratorIt commented on src/app/shared/services/download.service.ts
> +  blob(url: string, filename?: string): Observable<Blob> {
Not something I made, I am hesitant to remove it

2023-05-17 06:32 UTC, fcv-iteratorIt commented on src/app/shared/services/rest.service.ts
>  import { Observable, of, from } from 'rxjs';
Cleaned

2023-05-22 11:05 UTC, augusthjerrild approved these changes
Only one comment, but looks good!

2023-05-30 08:01 UTC, augusthjerrild approved these changes

2023-06-02 10:13 UTC, merged