Feature/1508 heights map
OS2iot/OS2iot-frontend pull request #159
Opened 2024-04-19 11:23 UTC by augusthjerrild

[IOT-1508]

2024-04-19 11:24 UTC, augusthjerrild commented on src/app/gateway/gateway-edit/gateway-edit.component.html
> +        <div>
This is the actual change :-)

2024-04-30 08:43 UTC, fcv-iteratorIt requested changes

2024-04-30 08:43 UTC, fcv-iteratorIt commented on src/app/shared/components/map/map.component.ts
> +    private marker: L.Marker;
IMO rename leaflet importet til leaflet

2024-04-30 08:43 UTC, fcv-iteratorIt commented on src/app/shared/components/map/map.component.ts
> +    private satelliteCenterLat = 56.07900207957074;
Probably add a commen on what this is, OR move it to a named constant in a constants file

2024-04-30 08:43 UTC, fcv-iteratorIt commented on src/app/shared/components/map/map.component.ts
> +    private changeLayerListener() {
rename to: `setupChangeLayerListener`

2024-04-30 08:43 UTC, fcv-iteratorIt commented on src/app/shared/components/map/map.component.ts
> +            var baseLayers: L.Control.LayersObject = {
Brug const

2024-04-30 08:43 UTC, fcv-iteratorIt commented on src/app/shared/components/map/map.component.ts
> +            var overlays: L.Control.LayersObject = {
brug const

2024-04-30 08:43 UTC, fcv-iteratorIt commented on src/app/shared/components/map/map.component.ts
> +                    var tempControl = layerControl as any;
brug const

2024-04-30 08:43 UTC, fcv-iteratorIt commented on src/assets/env.js
Den her bør ikke være i git

2024-05-02 05:48 UTC, fcv-iteratorIt approved these changes

2024-05-02 05:48 UTC, fcv-iteratorIt commented on src/assets/i18n/da.json
> +    "OPERATIONAL-NAME": "Driftsansvarlig",
Der er lige gået et eller andet galt i formatting her

2024-05-02 06:02 UTC, merged