Feature/1583 move application
OS2iot/OS2iot-frontend pull request #167
Opened 2024-09-10 13:59 UTC by MadsApollo

Added dialog to change application organization via permission ids.

2024-09-12 10:06 UTC, MadsApollo commented on src/app/applications/applications-list/applications-table/applications-table.component.ts
> +      location.reload();
Jeg ved ikke om der er en smart måde at fortælle at noget state i et andet komponent skal hentes, så har taget en nem løsning bare at reloade... der er også gjort i næste pr

2024-09-12 11:38 UTC, fcv-iteratorIt requested changes

2024-09-12 11:38 UTC, fcv-iteratorIt commented on src/app/applications/applications-list/applications-table/applications-table.component.ts
> +      location.reload();
Det virker smooth nok imo med reload (testede lige at splice, men det viker umiddelbart ikke)

2024-09-12 11:38 UTC, fcv-iteratorIt commented on src/app/applications/application-detail/application-detail.component.ts
> +  private dropdownButtonExtraOptionsHandlers: Map<number, () => void> = new Map();
Har du da en situation her i hvor du har brug for mere end én handler? 

Hvis ja. så synes jeg du skal udvide `ExtraDropdownOption` til at have en onclick handler som kan blive defineret samme sted som du definerer label

2024-09-12 11:38 UTC, fcv-iteratorIt commented on src/app/applications/application-change-organization-dialog/application-change-organization-dialog.component.html
> +      id="userGroup"
Du har det samme id flere gange

2024-09-12 11:38 UTC, fcv-iteratorIt commented on src/app/applications/application-change-organization-dialog/application-change-organization-dialog.component.ts
> +    this.organizationsSubscription = this.organizationService.getMinimal().subscribe(res => {
Get minimal henter altid alle organisationer, man må kun flytte applikationer mellem organisationer man er applikations administrator på.

2024-09-12 11:38 UTC, fcv-iteratorIt commented on src/app/applications/application-change-organization-dialog/application-change-organization-dialog.component.ts
> +    this.permissionsSubscription = this.permissionService.getPermissions(1000, 0).subscribe(res => {
Dit get permissions her henter kun for de organisationer hvor brugeren har userAdmin rettighed, hvilket vil sige at man ikke altid kan se alle da permissions ikke er herakiske. (Den bør nok laves om til at lave et fetch for den givne organisations permissions hvis man er applikations admin). Alternativt skal vi lige diskutere den rettighed her med Mogens

2024-09-12 11:38 UTC, fcv-iteratorIt commented on src/app/shared/models/dialog.model.ts
> +  id: number;
Rename til applicationId

2024-09-12 11:59 UTC, MadsApollo commented on src/app/applications/application-detail/application-detail.component.ts
> +  private dropdownButtonExtraOptionsHandlers: Map<number, () => void> = new Map();
Jeg har ikke lige pt en situation med brug for mere end én handler, men det kunne der sagtens være. Jeg anvender den på samme måde i Feature/IOT-1209-MoveGateway, så det ville også gøre det nemmere der.

2024-09-13 06:31 UTC, fcv-iteratorIt approved these changes

2024-09-13 07:24 UTC, merged