Feature/iot 1530 datatarget log
OS2iot/OS2iot-frontend pull request #175
Opened 2024-09-19 11:22 UTC by Fritsen

2024-09-23 09:19 UTC, fcv-iteratorIt requested changes
Back knappen på de forskellige data target details sider swapper mellem tabs, den bør sende en tilbage til applikations oversigten. Ellers er resten godt

2024-09-23 09:19 UTC, fcv-iteratorIt commented on src/app/applications/datatarget/fiware/fiware-detail-tabs/fiware-detail-tabs.component.html
> +<app-top-bar *ngIf="datatarget" [data]="datatarget" [backButton]="backButton" [subPage]="true"
Data target typen er ikke tilladt på app-top-bar klassen

2024-09-24 08:46 UTC, Fritsen commented on src/app/applications/datatarget/fiware/fiware-detail-tabs/fiware-detail-tabs.component.html
> +<app-top-bar *ngIf="datatarget" [data]="datatarget" [backButton]="backButton" [subPage]="true"
Det har du totalt ret i. Det forstår jeg ikke, at mit IDE ikke viser. Får du den markeret af Rider?

2024-09-24 08:51 UTC, fcv-iteratorIt commented on src/app/applications/datatarget/fiware/fiware-detail-tabs/fiware-detail-tabs.component.html
> +<app-top-bar *ngIf="datatarget" [data]="datatarget" [backButton]="backButton" [subPage]="true"
Ja

2024-09-24 09:32 UTC, Fritsen commented on src/app/applications/datatarget/fiware/fiware-detail-tabs/fiware-detail-tabs.component.html
> +<app-top-bar *ngIf="datatarget" [data]="datatarget" [backButton]="backButton" [subPage]="true"
Fixed

2024-09-24 09:57 UTC, merged